### ISSUE TITLE
Check the HTML of the page

### ISSUE THREAD

**Issue by DiomedesDominguez** [xamarin/Xamarin.Forms-api-docs#209] opened 2020-06-28 04:00 UTC
There is an HTML code error.

![image](https://user-images.githubusercontent.com/4379316/85937514-3af50300-b8d2-11ea-9861-efe18efb75ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcy52aWV3Y2VsbA==
* Version Independent ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcy52aWV3Y2VsbA==
* Content: [ViewCell Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.viewcell?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/ViewCell.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ViewCell.xml)

**Comment by samhouts** [comment] 2020-06-29 21:57
Duplicate of #197

**Closed by samhouts** 2020-06-29 21:57 UTC
