### ISSUE TITLE
Bad links on the Navigation page

### ISSUE THREAD

**Issue by fatalistt** [xamarin/Xamarin.Forms-api-docs#205] opened 2020-06-20 21:29 UTC
NavigationPage
Page
TabbedPage
CarouselPage
MasterDetailPage

these links leads to pages with bad markup like that:
![image](https://user-images.githubusercontent.com/3428774/85212005-2905e400-b357-11ea-8467-b2f8066551cf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31212614-035f-01b6-d709-250173086778
* Version Independent ID: 354945b1-351b-bb2d-a8c4-878650f521d0
* Content: [Xamarin.Forms Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by cheles** [comment] 2020-06-26 08:05
duplicate of https://github.com/xamarin/Xamarin.Forms-api-docs/issues/197

**Closed** 2020-06-29 21:58 UTC
