### ISSUE TITLE
Same description given for the different values

### ISSUE THREAD

**Issue by archchancellor** [xamarin/Xamarin.Forms-api-docs#206] opened 2020-06-21 20:33 UTC
Hello,

Under Fields section, for the values True and False same description is given: "Indicates that the status bar should not be hidden."

Regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcy5wbGF0Zm9ybWNvbmZpZ3VyYXRpb24uaW9zc3BlY2lmaWMuc3RhdHVzYmFyaGlkZGVubW9kZQ==
* Version Independent ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcy5wbGF0Zm9ybWNvbmZpZ3VyYXRpb24uaW9zc3BlY2lmaWMuc3RhdHVzYmFyaGlkZGVubW9kZQ==
* Content: [StatusBarHiddenMode Enum (Xamarin.Forms.PlatformConfiguration.iOSSpecific)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.iosspecific.statusbarhiddenmode?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms.PlatformConfiguration.iOSSpecific/StatusBarHiddenMode.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.PlatformConfiguration.iOSSpecific/StatusBarHiddenMode.xml)

**Comment by rachelkang** [comment] 2020-10-20 22:21
Thanks for submitting this issue! We'll be sure to get to it.
Closing now since it's a duplicate of #148

**Closed by rachelkang** 2020-10-20 22:21 UTC
