### ISSUE TITLE
Unescaped meta tag content breaking the HTML

### ISSUE THREAD

**Issue by gewarren** [xamarin/Xamarin.Forms-api-docs#203] opened 2020-06-17 19:20 UTC
---
**Issue moved from MicrosoftDocs/feedback#2829**
- Please respond to @aptwebapps.

---

_From @aptwebapps on Sunday, June 7, 2020 11:47:49 AM_

**Describe the bug**
The description meta tag's content is not escaped and is creating invalid HTML

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.bindableobject?view=xamarin-forms
2. See meta content along with garbage tag close displayed at top of page

**Expected behavior**
Meta tag content should not be HTML

**Screenshots**
![broken_meta_tag](https://user-images.githubusercontent.com/195165/83967834-a1de5800-a8e2-11ea-84fb-795a61c83597.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 77

**Smartphone (please complete the following information):**
Untested

**Additional context**
None

**Comment by gewarren** [comment] 2020-06-17 19:20
---
**Issue moved from MicrosoftDocs/feedback#2829**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Sunday, June 7, 2020 11:47:50 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by cheles** [comment] 2020-06-26 08:04
reported also here: 
https://github.com/xamarin/Xamarin.Forms-api-docs/issues/197
https://github.com/xamarin/Xamarin.Forms-api-docs/issues/199

**Comment by samhouts** [comment] 2020-06-29 21:58
Duplicate of #197

**Closed by samhouts** 2020-06-29 21:58 UTC
