### ISSUE TITLE
page header is not correct 

### ISSUE THREAD

**Issue by gewarren** [xamarin/Xamarin.Forms-api-docs#202] opened 2020-06-17 17:59 UTC
---
**Issue moved from MicrosoftDocs/feedback#2848**
- Please respond to @behroozbc.

---

_From @behroozbc on Wednesday, June 10, 2020 9:20:02 PM_

**Describe the bug**
page dont show correct 
**To Reproduce**
1. Search in search engine HasUnevenRows
2. open page of ms docs 
3. See error

**Expected behavior**
show correct like other page

**Screenshots**
![image](https://user-images.githubusercontent.com/20381616/84319654-9bbbd600-ab85-11ea-8743-4ad1b42d2672.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft edge
 - Version 83

**Comment by gewarren** [comment] 2020-06-17 19:19
Also see https://github.com/MicrosoftDocs/feedback/issues/2829.

**Comment by samhouts** [comment] 2020-06-29 21:58
Duplicate of #197

**Closed by samhouts** 2020-06-29 21:58 UTC
