### ISSUE TITLE
Page not loading correctly

### ISSUE THREAD

**Issue by pablo-gasparinid** [xamarin/Xamarin.Forms-api-docs#201] opened 2020-06-17 02:17 UTC
[Enter feedback here]
This page shows a closing html tag at the top left. I suspect is the reason why the TOC is not loading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcy5zY3JvbGx2aWV3LnNjcm9sbHRvYXN5bmM=
* Version Independent ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcy5zY3JvbGx2aWV3LnNjcm9sbHRvYXN5bmM=
* Content: [ScrollView.ScrollToAsync Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.scrollview.scrolltoasync?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/ScrollView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ScrollView.xml)

**Comment by samhouts** [comment] 2020-06-29 21:59
Duplicate of #197

**Closed by samhouts** 2020-06-29 21:59 UTC
