### ISSUE TITLE
Please add correct value to "Applies to:"

### ISSUE THREAD

**Issue by Alex-Witkowski** [xamarin/Xamarin.Forms-api-docs#52] opened 2019-04-02 10:32 UTC
When you need to work with "older" framework versions it would be really helpful to see the version some feature was added. 
For ImageSource it shows "Latest" but it is in Xamarin.Forms at least from version 2.2 on the other side - FontImageSource (https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.fontimagesource?view=xamarin-forms) also says "Latest" and there it is (at the moment) true with Xamarin.Froms 3.6.

If there is a way to edit the "Applies to:" please show it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01339d1b-f817-f10c-0b43-4d6816c5eadc
* Version Independent ID: 094cd696-88c5-7cf4-3f35-a7997fa82b35
* Content: [ImageSource Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.imagesource?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/ImageSource.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ImageSource.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mattleibow** [comment] 2020-10-21 21:55
Even though this is older, closing this as a duplicate of #174

**Closed by mattleibow** 2020-10-21 21:55 UTC
