### ISSUE TITLE
Malformed meta header

### ISSUE THREAD

**Issue by peterfoot** [xamarin/Xamarin.Forms-api-docs#199] opened 2020-06-16 09:36 UTC
The page header is showing random text because of malformed meta header

```
<meta property="og:description" content="<p sourcefile="api/Xamarin.Forms.yml" sourcestartlinenumber="1" jsonPath="/summary">Cross-platform, natively-backed UI toolkit.</p>
--
  | " />
```

![xam docs error](https://user-images.githubusercontent.com/3985053/84758315-31f45f80-afbd-11ea-9724-771bba1029db.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcw==
* Version Independent ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcw==
* Content: [Xamarin.Forms Namespace](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms?view=xamarin-forms)
* Content Source: [docs/ns-Xamarin.Forms.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/ns-Xamarin.Forms.xml)

**Comment by cheles** [comment] 2020-06-26 07:44
duplicate of https://github.com/xamarin/Xamarin.Forms-api-docs/issues/199

**Comment by samhouts** [comment] 2020-06-29 21:59
Duplicate of #197

**Closed by samhouts** 2020-06-29 21:59 UTC
