### ISSUE TITLE
HTML Tag Error on Microsoft Website

### ISSUE THREAD

**Issue by mrhery** [xamarin/Xamarin.Forms-api-docs#208] opened 2020-06-28 03:13 UTC
Hi, there's an erro rin Microsoft / Xamarin Form Documentation.

here's the url
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.picker?view=xamarin-forms

![Screenshot_2020-06-28 Picker Class (Xamarin Forms)](https://user-images.githubusercontent.com/20160636/85936780-53940600-b930-11ea-9d5f-c2b0981055a6.png)

**Comment by samhouts** [comment] 2020-06-29 21:58
Duplicate of #197

**Closed by samhouts** 2020-06-29 21:58 UTC
